### ISSUE TITLE
自动预标注可以支持ppdet的ppyoloe+和ppyolov7的微调自定义分类模型吗？

### ISSUE THREAD

**Issue by lifw555** [PaddleCV-SIG/PaddleLabel-ML#8]
如题，谢谢。

使用场景：
1、先手动标注一些图。
2、用这些标注好的数据，进行训练，得到训练好的模型。
3、用训练好的模型，导入到[PaddleLabel-ML](https://github.com/PaddleCV-SIG/PaddleLabel-ML)中。
4、使用这个模型，继续自动预标注一些新的图片，手动修改标注错误的标注，然后保存数据集。
5、再用这些数据进行训练。
6、循环2~5，直到所有图片标注完毕。

目的是提高标注效率。

**Comment by lifw555** [comment]
或者，这种方式，是不是最好的方式呢？

**Comment by linhandev** [comment]
您好，抱歉这么久才看到，后面有issue的话建议在PaddleLabel repo下面开，那边我们看的勤一些 :laughing: 

https://github.com/PaddleCV-SIG/PaddleLabel/issues

目前我们的ml后端只支持调用几个预训练模型进行推理，这种主动学习流程我们未来有计划添加支持，个人感觉这种流程对效率的提升是很明显的，不过最近我们主要的开发精力还集中在完善基础标注功能方面，估计这个还需要等一段时间

机器学习方面大致的计划是
1. 近期进一步完善paddlelabel和det,seg等套件的融合，支持套件的数据集格式和测试导出后使用套件训练，完善文档
2. 下一步会是支持使用更多套件中的模型进行推理
3. 最后会是你提到的这种，使用标注中的数据集进行训练，训练完成后使用模型进行推理

**Comment by lifw555** [comment]
了解，感谢！

**Comment by Kitzzaaa** [comment]
@linhandev 请问最进开发出可以加载自己训练好的模型的paddlelabel_ml了吗？
